### ISSUE TITLE
Training parameters error

### ISSUE THREAD

**Issue by ccCamila** [jianweiguo/local3Ddescriptorlearning#8]
Hi! When I pre-train this model, I find these following parameters which have a "?"  inside. 
I'd like to ask what's the meaning of these parameters? Is it wrong to have "?" inside?
(on the first line)
`python3 train_softmax256.py `

```
  [TL] **InputLayer  input: (?, 32, 32, 31)**
  [TL] Conv2dLayer conv2_1: shape:[3, 3, 31, 128] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn2_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool2: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:max_pool
  [TL] Conv2dLayer conv3_1: shape:[3, 3, 128, 256] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn3_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool3: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:max_pool
  [TL] Conv2dLayer conv4_1: shape:[3, 3, 256, 512] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn4_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool4: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:avg_pool
  [TL] FlattenLayer flatten: 8192
  [TL] DenseLayer  fc1_relu: 512 identity
  [TL] BatchNormLayer bn_fc: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] DenseLayer  128d_embedding: 128 identity
  [TL] InputLayer  input: (?, 32, 32, 31)
  [TL] Conv2dLayer conv2_1: shape:[3, 3, 31, 128] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn2_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool2: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:max_pool
  [TL] Conv2dLayer conv3_1: shape:[3, 3, 128, 256] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn3_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool3: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:max_pool
  [TL] Conv2dLayer conv4_1: shape:[3, 3, 256, 512] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn4_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool4: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:avg_pool
  [TL] FlattenLayer flatten: 8192
  [TL] DenseLayer  fc1_relu: 512 identity
  [TL] BatchNormLayer bn_fc: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] DenseLayer  128d_embedding: 128 identity
  [TL] InputLayer  input: (?, 32, 32, 31)
  [TL] Conv2dLayer conv2_1: shape:[3, 3, 31, 128] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn2_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool2: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:max_pool
  [TL] Conv2dLayer conv3_1: shape:[3, 3, 128, 256] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn3_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool3: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:max_pool
  [TL] Conv2dLayer conv4_1: shape:[3, 3, 256, 512] strides:[1, 1, 1, 1] pad:SAME act:identity
  [TL] BatchNormLayer bn4_1: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] PoolLayer   pool4: ksize:[1, 2, 2, 1] strides:[1, 2, 2, 1] padding:SAME pool:avg_pool
  [TL] FlattenLayer flatten: 8192
  [TL] DenseLayer  fc1_relu: 512 identity
  [TL] BatchNormLayer bn_fc: decay:0.900000 epsilon:0.000100 act:leaky_relu is_train:True
  [TL] DenseLayer  128d_embedding: 128 identity
  [TL] DenseLayer  feature: 256 identity
  [*] geting variables with W_conv2d
  [*] geting variables with 128d_embedding/W
Successfully initialized global variables.
  param   0: (3, 3, 31, 128) (mean: 0.00010006329830503091, median: 0.000174839049577713, std: 0.037381887435913086)   model/conv2_1/W_conv2d:0
  param   1: (128,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/conv2_1/b_conv2d:0
  param   2: (128,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn2_1/beta:0
  param   3: (128,)          (mean: 1.000234842300415 , median: 1.0000677108764648, std: 0.0019712939392775297)   model/bn2_1/gamma:0
  param   4: (128,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn2_1/moving_mean:0
  param   5: (128,)          (mean: 1.0               , median: 1.0               , std: 0.0               )   model/bn2_1/moving_variance:0
  param   6: (3, 3, 128, 256) (mean: 2.1745681806351058e-05, median: 7.917359471321106e-05, std: 0.024044597521424294)   model/conv3_1/W_conv2d:0
  param   7: (256,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/conv3_1/b_conv2d:0
  param   8: (256,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn3_1/beta:0
  param   9: (256,)          (mean: 0.9999599456787109, median: 1.0000708103179932, std: 0.0020056217908859253)   model/bn3_1/gamma:0
  param  10: (256,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn3_1/moving_mean:0
  param  11: (256,)          (mean: 1.0               , median: 1.0               , std: 0.0               )   model/bn3_1/moving_variance:0
  param  12: (3, 3, 256, 512) (mean: -1.678668922977522e-05, median: -2.754293382167816e-05, std: 0.017009815201163292)   model/conv4_1/W_conv2d:0
  param  13: (512,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/conv4_1/b_conv2d:0
  param  14: (512,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn4_1/beta:0
  param  15: (512,)          (mean: 1.0000686645507812, median: 1.0000386238098145, std: 0.002114894799888134)   model/bn4_1/gamma:0
  param  16: (512,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn4_1/moving_mean:0
  param  17: (512,)          (mean: 1.0               , median: 1.0               , std: 0.0               )   model/bn4_1/moving_variance:0
  param  18: (8192, 512)     (mean: -8.327621617354453e-05, median: -5.361372313927859e-05, std: 0.0879683718085289)   model/fc1_relu/W:0
  param  19: (512,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/fc1_relu/b:0
  param  20: (512,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn_fc/beta:0
  param  21: (512,)          (mean: 1.000016212463379 , median: 0.9999938011169434, std: 0.0020999941043555737)   model/bn_fc/gamma:0
  param  22: (512,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/bn_fc/moving_mean:0
  param  23: (512,)          (mean: 1.0               , median: 1.0               , std: 0.0               )   model/bn_fc/moving_variance:0
  param  24: (512, 128)      (mean: 0.0003383695147931576, median: 0.0008144766325131059, std: 0.08786192536354065)   model/128d_embedding/W:0
  param  25: (128,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   model/128d_embedding/b:0
  param  26: (128, 256)      (mean: 0.00017837490304373205, median: -0.00030296790646389127, std: 0.08813630044460297)   feature/W:0
  param  27: (256,)          (mean: 0.0               , median: 0.0               , std: 0.0               )   feature/b:0
  num of params: 5810304
  layer 0: Tensor("model/conv2_1/Identity:0", shape=(?, 32, 32, 128), dtype=float32)
  layer 1: Tensor("model/bn2_1/LeakyReLU/Maximum:0", shape=(?, 32, 32, 128), dtype=float32)
  layer 2: Tensor("model/pool2:0", shape=(?, 16, 16, 128), dtype=float32)
  layer 3: Tensor("model/conv3_1/Identity:0", shape=(?, 16, 16, 256), dtype=float32)
  layer 4: Tensor("model/bn3_1/LeakyReLU/Maximum:0", shape=(?, 16, 16, 256), dtype=float32)
  layer 5: Tensor("model/pool3:0", shape=(?, 8, 8, 256), dtype=float32)
  layer 6: Tensor("model/conv4_1/Identity:0", shape=(?, 8, 8, 512), dtype=float32)
  layer 7: Tensor("model/bn4_1/LeakyReLU/Maximum:0", shape=(?, 8, 8, 512), dtype=float32)
  layer 8: Tensor("model/pool4:0", shape=(?, 4, 4, 512), dtype=float32)
  layer 9: Tensor("model/flatten:0", shape=(?, 8192), dtype=float32)
  layer 10: Tensor("model/fc1_relu/Identity:0", shape=(?, 512), dtype=float32)
  layer 11: Tensor("model/bn_fc/LeakyReLU/Maximum:0", shape=(?, 512), dtype=float32)
  layer 12: Tensor("model/128d_embedding/Identity:0", shape=(?, 128), dtype=float32)
  layer 13: Tensor("feature/Identity:0", shape=(?, 256), dtype=float32)
   learning_rate: 0.001000
   batch_size: 512

```

And then I met the error. I found that error occurs because of this line:
```
    for keypoint_id in selected_keypoints:
          train_gi, train_label = sess.run(train_next_element_list[keypoint_id])
```
This is line:466 in the file ` train_softmax256.py`

The error looks like this. I think this might be related to "?" mentioned above.
```
Traceback (most recent call last):
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[Node: IteratorGetNext_382 = IteratorGetNext[output_shapes=[[?,32,32,31], [?]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_382)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_softmax256.py", line 468, in <module>
    train_gi, train_label = sess.run(train_next_element_list[keypoint_id])
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[Node: IteratorGetNext_382 = IteratorGetNext[output_shapes=[[?,32,32,31], [?]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_382)]]

Caused by op 'IteratorGetNext_382', defined at:
  File "train_softmax256.py", line 432, in <module>
    train_next_element = train_iter.get_next()
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/local3Ddescriptorlearning-master/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
         [[Node: IteratorGetNext_382 = IteratorGetNext[output_shapes=[[?,32,32,31], [?]], output_types=[DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_382)]]


```

Would you please help me! Thank you very much!

**Comment by ccCamila** [comment]
Is there something wrong with batch_size in the file `train_softmax256.py` from line 324 to line 351

```
# Placeholder setup
# [batch_size, height, width, channels]
anchor_placeholder = tf.placeholder(
    dtype=tf.float32,
    shape=[None, args.gi_size, args.gi_size, args.gi_channel])  # [batch_size, height, width, channels]

positive_placeholder = tf.placeholder(
    dtype=tf.float32,
    shape=[None, args.gi_size, args.gi_size, args.gi_channel])  # [batch_size, height, width, channels]

negative_placeholder = tf.placeholder(
    dtype=tf.float32,
    shape=[None, args.gi_size, args.gi_size, args.gi_channel])  # [batch_size, height, width, channels]

anchor_label_placeholder = tf.placeholder(
    dtype=tf.int32,
    shape=[None])  # [batch_size, height, width, channels]
```

Why is batch_size is none?
